### PR TITLE
A simple SQL formatter

### PR DESCRIPTION
**Pull request by RobGordijn**
I have created a simple SQL formatter.

### CODE REVIEW

**Comment by abhibeckert** [comment]
Can you embed the code in the bundle instead of calling to your server?

**Comment by RobGordijn** [comment]
Not really. It's created with a set of PHP modules/classes. This was created because the normal 'Format SQL' still wasn't fixed (and the PR is available).
If you don't allow external requests, I will gladly take down this PR and look for an embedded implementation.

**Comment by abhibeckert** [comment]
We have had problems with external requests in other bundles so I'd prefer to avoid them. Bundles can contain PHP code, if you'd like to share it I can do the work to pull it in?

**Comment by dmoagx** [comment]
>  This was created because the normal 'Format SQL' still wasn't fixed (and the PR is available).

I've not yet seen a valid fix for the existing SQL formatter.
See: https://github.com/sequelpro/sequelpro/issues/1988#issuecomment-144577691

**Comment by RobGordijn** [comment]
All clear. Closing this PR and working on a new one that includes the PHP ;)

**Pull request closed without merging**
