### PR TITLE
Added a Base64 decode bundle

### PR DESCRIPTION
**Pull request by gido**

### CODE REVIEW

**Comment by dmoagx** [comment]
I think you've got an XSS hole there.

**Comment by gido** [comment]
Could be. But I dont want to filter the output (I use this to have an accurate preview of a base64 encoded value).

Ideally it would be nice to have a new output type: "Show as Text" (without HTML rendering).

Any advice ?

**Comment by dmoagx** [comment]
If you want an accurate output you need to fix the XSS. Otherwise, as soon as the base64 contains a `<` character strange things would happen.

Here is what your code will display for the encoded string
```
<h1>Uh oh!</h1>
```
bildschirmfoto 2015-05-29 um 22 11 34 775

**Comment by abhibeckert** [comment]
Supplanted by #20

**Comment by gido** [comment]
👍

**Pull request closed without merging**
